name: "Create configs and upload"


runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: replace addresses
      shell: bash
      run: |
        echo "replacing"
        sed -i -e "s/{APP1_EXTERNAL_ADDRESS}/${{ github.event.inputs.APP_1_EXTERNAL_ADDRESS || env.DEFAULT_APP_1_EXTERNAL_ADDRESS }}/g" \
        -e "s/{APP2_INTERNAL_ADDRESS}/${{ github.event.inputs.APP_2_INTERNAL_ADDRESS || env.DEFAULT_APP_2_INTERNAL_ADDRESS }}/g" \
        ./configs/config1.yml
        sed -i -e "s/{APP1_NAME}/test/g" ./configs/config2.yml

    - name: Copy config to a different path
      shell: bash
      run: |
        mkdir ./generated/
        cp ./configs/* ./dir/generated/

    - name: Upload config1.yml
      uses: actions/upload-artifact@v3
      with:
        name: configs
        path: |
          ./dir/generated/