name: Dynamically creating files

on: 
  workflow_dispatch:
    inputs:
      APP_1_EXTERNAL_ADDRESS:
        description: "IP of FQDN"
        required: true
        default: "127.0.0.1"
      APP_2_INTERNAL_ADDRESS:
        description: "Internal IP"
        required: true
        default: "172.0.0.1"
      VERSION:
        description: "version of deploy"
        required: true
        default: 
  push:

env:
  DEFAULT_APP_1_EXTERNAL_ADDRESS: "127.0.0.1"
  DEFAULT_APP_2_INTERNAL_ADDRESS: "172.0.0.1"
  DEFAULT_VERSION: "v1"

jobs:
  create_config:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create configs for v1
        if: ${{ inputs.VERSION == 'v1' || env.DEFAULT_VERSION == 'v1' && github.event_name == 'push' }}
        uses: ./.github/actions/create-config/v1
        
      - name: Create configs for v2
        if: ${{ inputs.VERSION == 'v2' }}
        uses: ./.github/actions/create-config/v2
        
  read_config:
    runs-on: ubuntu-22.04
    needs: create_config
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download config
        uses: actions/download-artifact@v3
        with:
          name: configs

      - name: Cat config
        run: |
          cat config1.yml
          cat ./config2.yml
        continue-on-error: true



